services:
  - type: web
    name: gemini-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GEMINI_API_KEY
        value: your-gemini-api-key-here
